FROM ubuntu
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_4.x | bash && \
    apt-get install -y nodejs && \
    npm install -g serverless

WORKDIR /root
